### ISSUE TITLE
신규버전 권한 이슈(안드로이드,apk)

### ISSUE THREAD

**Issue by evons7** [sunho/SDStudio#24]
기종: S23U
-------------------------->
발견된 이슈: apk 설치시, 특정 권한에 대한 경고가 뜸- **보이스피싱 경고**
어떤 권한때문인진 모르겠으나 그냥 설치해서 사용해도 안전한지 궁금함

**Comment by sunho** [comment]
모든 파일 액세스 권한 때문인데 이게 없으면 문서에다가 파일을 저장 못해서... 코드가 전부 공개되어 있고 할일만 딱 하는데 믿음이 안가시면 안 쓰셔도 되용.
